name: alice_lightweight
description: Lightweight Alice version. Removed additional dependencies except dio.
version: 3.4.0
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  dio: ^5.0.0
  rxdart: ^0.27.7
  share_plus: ^7.1.0
  path_provider: ^2.0.12
